dependencies:
  build:
    - node:12.16.3

build_targets:
  - name: default
    commands:
      - npm install
      - npm test
    environment:
      - NODE_ENV=development
    host_only: true
  - name: deploy
    commands:
      - ./.yourbase_deploy.sh
    environment:
      - NODE_ENV=production

exec:
  commands:
    - npm start
  environment:
    default:
      - NODE_ENV=development
  host_only: true

ci:
  builds:
    - name: default
      build_target: default
ci:
  builds:
    - name: build
      build_target: default
    - name: deploy
      build_target: deploy
      when: branch is 'master'
