name: Deploy
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd web
          npm install
          rsync -Rr ./ ./dist
          find dist -name .gitignore -delete
          touch dist/.nojekyll # See https://stackoverflow.com/a/43487798/392225
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: web/dist
